version: '3.8'

services:
  api:
    build: 
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=info
      - AMAZON_ACCESS_KEY_ID=${AMAZON_ACCESS_KEY_ID}
      - AMAZON_SECRET_ACCESS_KEY=${AMAZON_SECRET_ACCESS_KEY}
      - AMAZON_REGION=${AMAZON_REGION}
      - AMAZON_DATASET_URL=${AMAZON_DATASET_URL}
    volumes:
      - ./services/api:/app
      - ./services/api/models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  models_data:
